version: '3.4'

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - .:/var/www/typewriter/:delegated
        ports:
            - 8000:80
        networks:
            - tw_net
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            MODE: development
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: typewriter
            DB_USER: typewriter
            DB_PASSWORD: password
        volumes:
            - .:/var/www/typewriter/:delegated
        networks:
            - tw_net
        depends_on:
            - mysql

    mysql:
        image: mariadb:latest
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
        environment:
            MYSQL_DATABASE: typewriter
            MYSQL_USER: typewriter
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - 3305:3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - tw_net

networks:
    tw_net:

volumes:
    db_data:
